builds:
  - id: hercules
    main: ./cmd/hercules/
    binary: hercules
    goos: [darwin, linux, freebsd, openbsd]
    goarch: [amd64, arm64]
    ldflags: >
      -s -w
      -X main.VERSION={{.Version}}
archives:
  - id: hercules
    builds: [hercules]
    format: tar.gz
    files:
      - README.md
      - LICENSE
dist: target/dist
release:
  github:
    owner: dbecorp
    name: hercules
  prerelease: auto
  disable: false
# brews:
#   - name: hercules
#     homepage: https://github.com/dbecorp/homebrew-hercules
